sudo: required
dist: trusty
addons:
    artifacts: {paths: [results]}
    apt: {sources: [google-chrome], packages: [google-chrome-stable]}
language: node_js
node_js:
    - '7'
cache:
    directories: [node_modules, bower_components, $HOME/.npm, $HOME/.cache]
before_script:
    - 'npm install'
before_deploy:
    - 'npm run build'
env:
    global: [NODE_ENV=testing, ARTIFACTS_BUCKET=javascript-automation, {secure: FWFTCTLpGaQ2lfHKPFADK5QjPmeSD2xS3HyH4Io01nx+b2Aanm8MoQskLcJVq+Dl+mAPcYUAkSSzoDzm6dMbH/ZR4blO/nWTXVkM02Mat3+1VI1qpeJhvd7ZGo6u/Eq5+ICBnkm7ocnWR6bJb5rgXItJN4wJLl55hdyJiHN3YSUhO/ba/E8mGJtfa6RXudfMFHMr1sx1UKzGU1FPH7E+OSv/dlYvRMvO7FJYV5ekuvOu12AMstPnk96KXyhfEYsfqiraiTJqCnnDdhCoir5viRHOk16L0j4XEN9Z8wTkdGS6bZZIqD5q84W4ISo8eqk5PriER8CkTVt1PG3NpAOfLg/srDQlIFoxqXeiNtCRApsd5V3mVot5THRUQPR+RWZi29tdOzy4ZiWmtYKOE5YZvb/6Z1md0LxoyuSEiid2Ld3rJPyGaWjStZo69hEz9C0NY+b+bl369mDYg7dglQBDb+iwQdw+fDhW4yK82GpJU+PpQX41MRLMRjPI1VRx+SnxZFFmp5SEq34wC+DvMaWkdSvuyztyfYwTk+yEQz7/BO3n3Qu3+3zg4gXfDKGjuo3uTwDt+JRSvEmA9fM8DPOgAgCH5jRA71pDdSSy3RRLQgzPxldNnLqyo0HgNzD4VTUZwjl8OcudLHH1sZ16pwakd2VHl52woSsL5iWelKjDOsQ=}, {secure: n95OZeMUeGpNduSTWpBJUMeZLY+v3iyAWUIsFPW9nZA5C9IlnOitI/it96PASyBY3sLQ+weXV6eRcRhO/O9ZLGImwS3g2Vx5ity7vcJlsBFKrmkCroBlE4UdeswVAMsFAunhL+3QoAukaKfYaIDta0lNPc/QHTGy86nNHhPJqITbrTzrKd9xfOltTNsEfUfm+oS0LaG8kahK+MK1gYuSizh9MNYeRZ64eoIm8A8hTo63GpIqMo6/y085uyuzzs266YKOeLsUJudtYNORGHwRaHTTHBNrOCygQq/bqm0XcUtLBjwXBUoMNwwruEXeS8ZusqI3FOhbTKeezpuCMTeZy4p549wBuDa0XSnAnDiojgDczFVj/EixY8dili8ueoT4P6L5Ww8QTJ/tIKPi2V7nF22isCyzxlm1nLHmQ7ld5D27S9epdm32z+uqpI0zLG+s2XaQYTb73XgFgLc6rvuQz3+ULZxJWHkVztKyGFqya3BpgCPJ5Sfuwv91jy1F7XORxxFEekvlAaHGt+O0DthRg7JegJHxwn0uQ7JJl0seEjNfi535N12V3ns1FGILdMjk8a4aomEj1n2Xwa9Trm0DeSvm4cyJX4YadgUJFohH0bIwiqQGNdINzI5REIlwSR1dOl2hsY39HIkQrbAXiDjndNzFE8th/oe+nguWDe6m1/c=}]
script:
    - 'npm run test'
notifications:
    webhooks: 'http://ec2-54-234-52-201.compute-1.amazonaws.com/automation/ci/build'
